[green_agent]
endpoint = "http://127.0.0.1:9999"

[[participants]]
role = "network_operator"
agentbeats_id = "some_agentbeats_id"
endpoint = "http://127.0.0.1:8000"

[config]
prompt_type = "zeroshot_base"
num_queries = 1
benchmark_path = "test_data.json"
regenerate_benchmark = false
output_dir = "output"
max_iterations = 10
num_switches = 2
num_hosts_per_subnet = 1

# Agent client configurations.
[[config.agent_client_configs]]
name = "azure-gpt"
base_url = "http://127.0.0.1:8000"
prompt_type = "zeroshot_cot"